-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 19:08:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema digitalgames_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema digitalgames_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `digitalgames_db` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema new_schema
-- -----------------------------------------------------
USE `digitalgames_db` ;

-- -----------------------------------------------------
-- Table `digitalgames_db`.`compatibilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`compatibilities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `releasedata` DATETIME NOT NULL,
  `img` TEXT NOT NULL,
  `fullname` VARCHAR(256) NOT NULL,
  `description` TEXT NOT NULL,
  `discount` INT(11) NOT NULL,
  `freeShipping` TINYINT(4) NOT NULL,
  `price` INT(11) NOT NULL,
  `capture1` TEXT NOT NULL,
  `capture2` TEXT NOT NULL,
  `capture3` TEXT NOT NULL,
  `capture4` TEXT NOT NULL,
  `video` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`compatibilities_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`compatibilities_has_products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `compatibilities_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compatibilities_has_products_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_compatibilities_has_products_compatibilities_idx` (`compatibilities_id` ASC) VISIBLE,
  CONSTRAINT `fk_compatibilities_has_products_compatibilities`
    FOREIGN KEY (`compatibilities_id`)
    REFERENCES `digitalgames_db`.`compatibilities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compatibilities_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `digitalgames_db`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`genders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`lenguages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`lenguages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`players` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`products_has_genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`products_has_genders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `products_id` INT(11) NOT NULL,
  `genders_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_has_genders_genders1_idx` (`genders_id` ASC) VISIBLE,
  INDEX `fk_products_has_genders_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_genders_genders1`
    FOREIGN KEY (`genders_id`)
    REFERENCES `digitalgames_db`.`genders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_has_genders_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `digitalgames_db`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`products_has_lenguages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`products_has_lenguages` (
  `products_id` INT(11) NOT NULL,
  `lenguages_id` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_products_has_lenguages_lenguages1_idx` (`lenguages_id` ASC) VISIBLE,
  INDEX `fk_products_has_lenguages_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_lenguages_lenguages1`
    FOREIGN KEY (`lenguages_id`)
    REFERENCES `digitalgames_db`.`lenguages` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_has_lenguages_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `digitalgames_db`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`products_has_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`products_has_players` (
  `products_id` INT(11) NOT NULL,
  `players_id` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_products_has_players_players1_idx` (`players_id` ASC) VISIBLE,
  INDEX `fk_products_has_players_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_players_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `digitalgames_db`.`players` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products_has_players_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `digitalgames_db`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digitalgames_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalgames_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `img_profile` BLOB NULL,
  `address` VARCHAR(100) NULL,
  `permissions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `permissions_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_users_permissions1_idx` (`permissions_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_permissions1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `digitalgames_db`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
