-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 09:45:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema digitalgames
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `digitalgames` ;

-- -----------------------------------------------------
-- Schema digitalgames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `digitalgames` DEFAULT CHARACTER SET utf8mb4 ;
USE `digitalgames` ;

-- -----------------------------------------------------
-- Table `digitalgames`.`compatibilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`compatibilities` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`compatibilities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`genders` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`genders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`lenguages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`lenguages` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`lenguages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`players` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`players` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`products` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `players` VARCHAR(250) NOT NULL,
  `releaseData` VARCHAR(250) NOT NULL,
  `img` TEXT NOT NULL,
  `fullName` VARCHAR(300) NOT NULL,
  `description` TEXT NOT NULL,
  `discount` INT(11) NOT NULL,
  `freeShipping` TINYINT(1) NOT NULL,
  `price` INT(11) NOT NULL,
  `capture1` TEXT NOT NULL,
  `capture2` TEXT NOT NULL,
  `capture3` TEXT NOT NULL,
  `capture4` TEXT NOT NULL,
  `video` TEXT NOT NULL,
  `compatibilities` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`shoppingcart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`shoppingcart` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`shoppingcart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` INT(11) NOT NULL,
  `total` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`users` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `fullName` VARCHAR(150) NOT NULL,
  `password` TEXT NOT NULL,
  `confirmPass` TEXT NOT NULL,
  `shoppingcart_id` INT(11) NOT NULL,
  `shoppingcart_id1` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`genders_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`genders_has_products` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`genders_has_products` (
  `genders_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`genders_id`, `products_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`players_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`players_has_products` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`players_has_products` (
  `players_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`players_id`, `products_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`lenguages_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`lenguages_has_products` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`lenguages_has_products` (
  `lenguages_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`lenguages_id`, `products_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`compatibilities_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`compatibilities_has_products` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`compatibilities_has_products` (
  `compatibilities_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`compatibilities_id`, `products_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `digitalgames`.`products_has_shoppingcart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digitalgames`.`products_has_shoppingcart` ;

CREATE TABLE IF NOT EXISTS `digitalgames`.`products_has_shoppingcart` (
  `products_id` INT(11) NOT NULL,
  `shoppingcart_id` INT(11) NOT NULL,
  PRIMARY KEY (`products_id`, `shoppingcart_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
